### ISSUE TITLE
Can I help with this repo?

### ISSUE THREAD

**Issue by ghost** [obscurerev/FNF-Mods-Web-Install#23]
Hi! I would love to help you with this repo. Since you're not really updating it anymore, I figured I could help with it. It doesn't seem that hard.

**Comment by obscurerev** [comment]
sorry for the delayed response, but yes if you want to help, u can fork it and I'll have it linked on here.

**Comment by drok28** [comment]
Ok. I've forked it. Now you can link it here.

**Comment by obscurerev** [comment]
it's linked

**Comment by F2-FlassyTTV** [comment]
ok guys ofc you can but make sure to ask the real maker of this porject
